# http://wiki.ros.org/global_planner#Parameters
GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.3
  visualize_potential: false
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1



# http://wiki.ros.org/base_local_planner#Parameters
TrajectoryPlannerROS:

  # Robot configuration
  acc_lim_x: 3.0
  acc_lim_theta: 2.0
  max_vel_x: 3
  min_vel_x: 0.2
  max_vel_theta: 4
  min_vel_theta: -4
  min_in_place_vel_theta: 0.1
  escape_vel: -0.5
  holonomic_robot: false

  # Goal tolerance
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: true

  # Forward simulation
  # sim_time: 3.0
  #sim_granularity: 0.05
  #angular_sim_granularity: 0.025
  #vx_samples: 3
  #vtheta_samples: 20

  # Trajectory scoring
  meter_scoring: true
  pdist_scale: 0.8
  gdist_scale: 0.6
  occdist_scale: 0.005
  heading_lookahead: 0.5
  heading_scoring: true
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: false

  # Oscillation
  oscillation_reset_dist: 0.1

  # Global plan
  prune_plan: true


