# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.5
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: false
  track_unknown_space: true  
  always_send_full_costmap: false

#  resolution: 0.08
#  width: 6.32
#  height: 6.64
#  origin_x: -3.025033 
#  origin_y: -3.138250

  plugins:
    - {name: static_layer,      type: "costmap_2d::StaticLayer"} 
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
