# http://wiki.ros.org/move_base#Parameters

# General parameters
#controller_frequency: 5
#planner_patience: 30
#controller_patience: 30
shutdown_costmaps: false
oscillation_timeout: 30
oscillation_distance: 0.5
planner_frequency: 0.0
max_planning_retries: 5

# Planner plugins
base_global_planner: global_planner/GlobalPlanner
base_local_planner: base_local_planner/TrajectoryPlannerROS

# Recovery behavior parameters
recovery_behavior_enabled: true
clearing_rotation_allowed: false
#conservative_reset_dist: 0.5
